---
- name: firewalld-config | Gather the installed package facts
  package_facts:
    manager: auto

- name: firewalld-config | Installing firewalld package if not already avaiable
  package:
    name: firewalld
    state: latest
  become: true
  when: "'firewalld' not in ansible_facts.packages"

- name: firewalld-config | Start firewalld service
  service:
    name: firewalld
    state: started
    enabled: true

- name: firewalld-config | Enable the RH Satellite service in firewalld permanently.
  firewalld:
    service: "{{ satellite_fw_service_name | default('ssh') }}"
    zone: public
    state: enabled
    permanent: true
    immediate: true

- name: firewalld-config | Redirect port 80 (HTTP) to 443 (HTTPS)
  firewalld:
    rich_rule: rule family=ipv4 forward-port port=80 protocol=tcp to-port=443
    zone:      public
    state:     enabled
    permanent: true
    immediate: true

- name: firewalld-config | Checking firewalld target policy
  command: "/usr/bin/firewall-cmd --zone public --get-target --permanent"
  changed_when: firewalld_public_policy.stdout != 'DROP'
  register: firewalld_public_policy


- name: firewalld-config | Enforce drop policy on firewall public zone
  command: "/usr/bin/firewall-cmd --zone public --set-target DROP --permanent"
  when: firewalld_public_policy.stdout != 'DROP'
  notify:
    - firewalld-reload
...
